### PR TITLE
Os integration

### PR DESCRIPTION
**Pull request by lonkamikaze**
This pull-request adds build-fixes for FreeBSD and OS integration additions:

- Set a home path from the build system
- Set a library lookup path that is separate from the base path

I can prepare a pull request without the latter two, if desired.

### CODE REVIEW

**Comment by ThomasBrierley** [comment]
Nice :)

Does this mean you are switching the FreeBSD port away from the standalone ioq3 port? I could never get that thing to work properly.

**Comment by lonkamikaze** [comment]
@ThomasBrierley 
> Does this mean you are switching the FreeBSD port away from the standalone ioq3 port? I could never get that thing to work properly.

Yes it does: https://reviews.freebsd.org/D8692

I simply didn't know the original code was available.

**Comment by ThomasBrierley** [comment]
Cool, thanks for bringing it up to date Kami :beer:

**Comment by ThomasBrierley** [comment]
Sure, I expect this will be reviewed as part of getting into the FreeBSD ports tree but i'll try compiling it separately too.

**Comment by ThomasBrierley** [comment]
Sorry forgot to reply to this, it built and appeared to run fine on my machine, although I don't run FreeBSD as my main OS anymore so didn't test it for very long.

**Pull request merged**
